[project]
name = "ofxstatement-schwab-json"
version = "0.8.0"
description = "ofxstatement plugin for Schwab JSON exports"
authors = [{ name = "Ed Wagner", email = "ed@edwagner.org" }]
requires-python = ">=3.10"
readme = "README.md"
keywords = [
    "ofx",
    "banking",
    "statement",
    "plugin",
    "ofxstatement",
    "schwab",
    "json",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Natural Language :: English",
    "Topic :: Office/Business :: Financial :: Accounting",
    "Topic :: Utilities",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]
dependencies = ["ofxstatement"]

[project.urls]
Homepage = "https://github.com/edwagner/ofxstatement-schwab-json/"

[project.entry-points.ofxstatement]
schwab_json = "ofxstatement_schwab_json.plugin:SchwabJsonPlugin"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "mypy",
    "pytest",
    "black",
    "exceptiongroup",
    "build",
    "tomli",
    "pytest-cov",
]

[tool.uv]
package = true
default-groups = "all"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[tool.uv.sources]
ofxstatement = { git = "https://github.com/kedder/ofxstatement.git", rev = "master" }
ofxstatement-schwab-json = { path = ".", editable = true }

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
